import pandas as pd
from datetime import datetime

# Load data
df = pd.read_csv('supply_chain.csv')
df['inventory_value'] = df['quantity_on_hand'] * df['unit_cost']
df['days_of_stock'] = df['quantity_on_hand'] / df['daily_demand']

def generate_alert_email():
    """Generate an alert email for critical inventory issues"""
    
    critical = df[df['days_of_stock'] < 14].sort_values('days_of_stock')
    
    if len(critical) == 0:
        email_body = """
SUBJECT: ✅ Inventory Status OK - All Products Well-Stocked

TO: supply.chain.manager@company.com
CC: logistics.team@company.com

---

INVENTORY STATUS REPORT - {date}

Status: ✅ ALL GREEN - No critical issues detected

All products have adequate stock levels (>14 days supply).

Total Inventory Value: ${total_value:,.0f}
Average Days of Stock: {avg_days:.1f} days

No action required at this time.

---
Generated by: Supply Chain Analytics System
        """.format(
            date=datetime.now().strftime('%Y-%m-%d %H:%M'),
            total_value=df['inventory_value'].sum(),
            avg_days=df['days_of_stock'].mean()
        )
    else:
        # Critical alert
        alert_items = ""
        for idx, row in critical.iterrows():
            shortage = row['reorder_point'] - row['quantity_on_hand']
            alert_items += f"""
    PRODUCT: {row['product_name']}
    ⚠️  DAYS UNTIL STOCKOUT: {row['days_of_stock']:.1f} days
    Current Stock: {row['quantity_on_hand']} units
    Daily Demand: {row['daily_demand']:.1f} units
    Need to Order: {shortage:.0f} units
    Supplier: {row['supplier']}
    Delivery Time: {row['delivery_time_days']} days
    ---
            """
        
        email_body = """
SUBJECT: 🔴 CRITICAL ALERT: Products Need Immediate Reorder!

TO: supply.chain.manager@company.com
CC: logistics.team@company.com
PRIORITY: HIGH

---

URGENT INVENTORY ACTION REQUIRED - {date}

{num_critical} product(s) need immediate reordering to prevent stockouts!

CRITICAL PRODUCTS:
{alert_items}

RECOMMENDED ACTIONS:
1. Contact suppliers immediately (see delivery times above)
2. Expedite shipping if possible
3. Review demand forecasts to prevent future occurrences
4. Consider safety stock increase for these products

SUMMARY:
Total Inventory Value: ${total_value:,.0f}
Products at Risk: {num_critical}
Critical (< 7 days): {num_critical_urgent}
Warning (7-14 days): {num_warning}

---
Generated by: Supply Chain Analytics System
Automated Alert System
        """.format(
            date=datetime.now().strftime('%Y-%m-%d %H:%M'),
            num_critical=len(critical),
            num_critical_urgent=len(df[df['days_of_stock'] < 7]),
            num_warning=len(df[(df['days_of_stock'] >= 7) & (df['days_of_stock'] < 14)]),
            total_value=df['inventory_value'].sum(),
            alert_items=alert_items
        )
    
    return email_body

def generate_daily_report():
    """Generate a daily inventory report"""
    
    report = f"""
╔════════════════════════════════════════════════════════════════════════════╗
║              DAILY SUPPLY CHAIN INVENTORY REPORT                           ║
║                      {datetime.now().strftime('%A, %B %d, %Y %H:%M')}                        ║
╚════════════════════════════════════════════════════════════════════════════╝

📊 OVERALL INVENTORY STATUS
───────────────────────────────────────────────────────────────────────────
  Total Inventory Value:        ${df['inventory_value'].sum():>15,.0f}
  Average Days of Stock:        {df['days_of_stock'].mean():>15.1f} days
  Total Daily Demand:           {df['daily_demand'].sum():>15.1f} units/day
  Number of Products:           {len(df):>15}
  Number of Suppliers:          {df['supplier'].nunique():>15}

🔴 CRITICAL (< 7 days of stock)
───────────────────────────────────────────────────────────────────────────
"""
    
    critical_urgent = df[df['days_of_stock'] < 7].sort_values('days_of_stock')
    if len(critical_urgent) > 0:
        for idx, row in critical_urgent.iterrows():
            report += f"  ⚠️  {row['product_name']:<20} {row['days_of_stock']:>6.1f} days  |  Supplier: {row['supplier']}\n"
    else:
        report += "  ✅ No critical items\n"
    
    report += f"""
⚠️  WARNING (7-14 days of stock)
───────────────────────────────────────────────────────────────────────────
"""
    
    warning = df[(df['days_of_stock'] >= 7) & (df['days_of_stock'] < 14)].sort_values('days_of_stock')
    if len(warning) > 0:
        for idx, row in warning.iterrows():
            report += f"  ⚠️  {row['product_name']:<20} {row['days_of_stock']:>6.1f} days  |  Supplier: {row['supplier']}\n"
    else:
        report += "  ✅ No warning items\n"
    
    report += f"""
💰 TOP VALUE PRODUCTS
───────────────────────────────────────────────────────────────────────────
"""
    
    top_value = df.nlargest(5, 'inventory_value')
    for rank, (idx, row) in enumerate(top_value.iterrows(), 1):
        pct = row['inventory_value'] / df['inventory_value'].sum() * 100
        report += f"  {rank}. {row['product_name']:<20} ${row['inventory_value']:>12,.0f}  ({pct:>5.1f}%)\n"
    
    report += f"""
📦 FASTEST MOVING PRODUCTS
───────────────────────────────────────────────────────────────────────────
"""
    
    top_demand = df.nlargest(5, 'daily_demand')
    for rank, (idx, row) in enumerate(top_demand.iterrows(), 1):
        report += f"  {rank}. {row['product_name']:<20} {row['daily_demand']:>6.1f} units/day\n"
    
    report += f"""
🏢 SUPPLIER STATUS
───────────────────────────────────────────────────────────────────────────
"""
    
    suppliers = df.groupby('supplier').agg({
        'inventory_value': 'sum',
        'delivery_time_days': 'mean'
    }).sort_values('inventory_value', ascending=False)
    
    for supplier, row in suppliers.iterrows():
        pct = row['inventory_value'] / df['inventory_value'].sum() * 100
        report += f"  {supplier:<20} ${row['inventory_value']:>12,.0f}  ({pct:>5.1f}%)  |  Avg Delivery: {row['delivery_time_days']:.1f} days\n"
    
    report += """
───────────────────────────────────────────────────────────────────────────
Generated by: Automated Supply Chain Analytics System
For questions or issues, contact: data.analytics@company.com
═════════════════════════════════════════════════════════════════════════════
"""
    
    return report

# Generate and save outputs
print("Generating alerts and reports...\n")

# Alert Email
alert_email = generate_alert_email()
print(alert_email)

# Save alert to file
with open(f'alert_{datetime.now().strftime("%Y%m%d_%H%M%S")}.txt', 'w', encoding='utf-8') as f:
    f.write(alert_email)
print("\n✅ Alert email saved to file")

# Daily Report
daily_report = generate_daily_report()
print("\n" + daily_report)

# Save report to file
with open(f'daily_report_{datetime.now().strftime("%Y%m%d_%H%M%S")}.txt', 'w', encoding='utf-8') as f:
    f.write(daily_report)
print("✅ Daily report saved to file")